---
title: Projects
toc: true
toc-title: ""
toc-location: left
---

```{r}
#| label: fn
#| echo: false
enlink_fa <- function(link, fa) {
  if (link == "") return(" ")
  paste0("[", fontawesome::fa(fa), "](", link, ")")
}
```

## Talks

Selected presentations. Made with Quarto or {xaringan}.

```{r}
#| label: talks
#| echo: false
talks <- read.csv("resources/talks.csv")
talks$Links <- paste(
  lapply(talks$slides_url, \(x) enlink_fa(x, "film")),
  lapply(talks$video_url,  \(x) enlink_fa(x, "video")),
  lapply(talks$blog_url,   \(x) enlink_fa(x, "pencil")),
  lapply(talks$source_url, \(x) enlink_fa(x, "github"))
)
talks[, c("Title", "Description", "Where", "When", "Links")] |> knitr::kable()
```

## R Packages

All are hosted on GitHub; none are on CRAN. The majority are concepts with no guarantees.

```{r}
#| label: packages
#| echo: false
pkgs <- read.csv("resources/packages.csv")
pkgs$Links <- paste(
  lapply(pkgs$source_url, \(x) enlink_fa(x, "github")),
  lapply(pkgs$blog_url,   \(x) enlink_fa(x, "pencil"))
)
pkgs$Name <- paste0("{", pkgs$Name, "}")
pkgs[, c("Name", "Description", "Links")] |> knitr::kable()
```

## Websites

```{r}
#| label: websites
#| echo: false
tibble::tribble(
  ~Name, ~What, ~Tools, ~Links,
  # 
  "matt-dray.com", 
  "This website",
  "Quarto, Netlify",
  paste0(
    "[",  fontawesome::fa("globe"), "](https://www.matt-dray.com/) ",
    "[",  fontawesome::fa("github"), "](https://www.github.com/matt-dray/personal-site/) ",
    "[",  fontawesome::fa("pencil"), "](https://www.rostrum.blog/posts/2020-12-08-postcard/)"
  ),
  #
  "rostrum.blog", 
  "Japes with R: tutorials, ephemera, memes",
  "Quarto, Netlify",
  paste0(
    "[",  fontawesome::fa("globe"), "](https://www.rostrum.blog/) ",
    "[",  fontawesome::fa("github"), "](https://www.github.com/matt-dray/rostrum-blog-2/) ",
    "[",  fontawesome::fa("pencil"), "](https://www.rostrum.blog/posts/2023-08-26-cheerio-blogdown/)"
  ),
  #
  "faxcrayon.art", 
  "This website",
  "RMarkdown, {bs4cards}, GitHub Pages",
  paste0(
    "[",  fontawesome::fa("globe"), "](https://www.faxcrayon.art/) ",
    "[",  fontawesome::fa("github"), "](https://www.github.com/matt-dray/faxcrayon/) ",
    "[",  fontawesome::fa("pencil"), "](https://www.rostrum.blog/posts/2021-07-25-faxcrayon/)"
  ),
) |> 
  knitr::kable()
```

## Shiny apps

## Other
